// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_helloScreen_screen_init(void)
{
ui_helloScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_helloScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_headerHelloText = lv_label_create(ui_helloScreen);
lv_obj_set_width( ui_headerHelloText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_headerHelloText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_headerHelloText, LV_ALIGN_CENTER );
lv_label_set_text(ui_headerHelloText,"HOLA");
lv_obj_set_style_text_font(ui_headerHelloText, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rightHelloButton = lv_imgbtn_create(ui_helloScreen);
lv_imgbtn_set_src(ui_rightHelloButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowforward_png, NULL);
lv_imgbtn_set_src(ui_rightHelloButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowforward_png, NULL);
lv_obj_set_width( ui_rightHelloButton, lv_pct(10));
lv_obj_set_height( ui_rightHelloButton, lv_pct(15));
lv_obj_set_x( ui_rightHelloButton, lv_pct(40) );
lv_obj_set_y( ui_rightHelloButton, lv_pct(0) );
lv_obj_set_align( ui_rightHelloButton, LV_ALIGN_CENTER );

ui_leftHelloButton = lv_imgbtn_create(ui_helloScreen);
lv_imgbtn_set_src(ui_leftHelloButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowback_png, NULL);
lv_imgbtn_set_src(ui_leftHelloButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowback_png, NULL);
lv_obj_set_width( ui_leftHelloButton, lv_pct(10));
lv_obj_set_height( ui_leftHelloButton, lv_pct(15));
lv_obj_set_x( ui_leftHelloButton, lv_pct(-40) );
lv_obj_set_y( ui_leftHelloButton, lv_pct(0) );
lv_obj_set_align( ui_leftHelloButton, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_rightHelloButton, ui_event_rightHelloButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_leftHelloButton, ui_event_leftHelloButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_helloScreen, ui_event_helloScreen, LV_EVENT_ALL, NULL);

}
