// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_infoScreenTypeFood_screen_init(void)
{
ui_infoScreenTypeFood = lv_obj_create(NULL);
lv_obj_clear_flag( ui_infoScreenTypeFood, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_infoScreenTypeFoodHeader = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenTypeFoodHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenTypeFoodHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenTypeFoodHeader, lv_pct(-25) );
lv_obj_set_y( ui_infoScreenTypeFoodHeader, lv_pct(-15) );
lv_obj_set_align( ui_infoScreenTypeFoodHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenTypeFoodHeader,"Tipo de alimento");

ui_infoScreenQuantityHeader = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenQuantityHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenQuantityHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenQuantityHeader, lv_pct(-25) );
lv_obj_set_y( ui_infoScreenQuantityHeader, lv_pct(0) );
lv_obj_set_align( ui_infoScreenQuantityHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenQuantityHeader,"Cantidad");

ui_infoScreenTimeHeader = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenTimeHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenTimeHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenTimeHeader, lv_pct(-25) );
lv_obj_set_y( ui_infoScreenTimeHeader, lv_pct(15) );
lv_obj_set_align( ui_infoScreenTimeHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenTimeHeader,"Tiempo");

ui_infoScreenInitButton = lv_btn_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenInitButton, 100);
lv_obj_set_height( ui_infoScreenInitButton, 50);
lv_obj_set_x( ui_infoScreenInitButton, lv_pct(-35) );
lv_obj_set_y( ui_infoScreenInitButton, lv_pct(35) );
lv_obj_set_align( ui_infoScreenInitButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_infoScreenInitButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_infoScreenInitButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_infoScreenInitButton);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"Iniciar");

ui_Button3 = lv_btn_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, lv_pct(35) );
lv_obj_set_y( ui_Button3, lv_pct(35) );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_infoScreenForceButton = lv_label_create(ui_Button3);
lv_obj_set_width( ui_infoScreenForceButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenForceButton, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_infoScreenForceButton, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenForceButton,"Forzar\n Distribucion");
lv_obj_set_style_text_align(ui_infoScreenForceButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_infoScreenConfiguratioButton = lv_btn_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenConfiguratioButton, 110);
lv_obj_set_height( ui_infoScreenConfiguratioButton, 50);
lv_obj_set_x( ui_infoScreenConfiguratioButton, lv_pct(12) );
lv_obj_set_y( ui_infoScreenConfiguratioButton, lv_pct(35) );
lv_obj_set_align( ui_infoScreenConfiguratioButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_infoScreenConfiguratioButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_infoScreenConfiguratioButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_infoScreenConfiguratioButton);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Configuracion");

ui_infoScreenStopButton = lv_btn_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenStopButton, 100);
lv_obj_set_height( ui_infoScreenStopButton, 50);
lv_obj_set_x( ui_infoScreenStopButton, lv_pct(-12) );
lv_obj_set_y( ui_infoScreenStopButton, lv_pct(35) );
lv_obj_set_align( ui_infoScreenStopButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_infoScreenStopButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_infoScreenStopButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label14 = lv_label_create(ui_infoScreenStopButton);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"Parar");

ui_infoScreenTypeFoodInfo = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenTypeFoodInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenTypeFoodInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenTypeFoodInfo, lv_pct(5) );
lv_obj_set_y( ui_infoScreenTypeFoodInfo, lv_pct(-15) );
lv_obj_set_align( ui_infoScreenTypeFoodInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenTypeFoodInfo,"Croquetas");

ui_infoScreenTimeInfo = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenTimeInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenTimeInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenTimeInfo, lv_pct(5) );
lv_obj_set_y( ui_infoScreenTimeInfo, lv_pct(15) );
lv_obj_set_align( ui_infoScreenTimeInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenTimeInfo,"2");

ui_infoScreenQuantityInfo = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenQuantityInfo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenQuantityInfo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenQuantityInfo, lv_pct(5) );
lv_obj_set_y( ui_infoScreenQuantityInfo, lv_pct(0) );
lv_obj_set_align( ui_infoScreenQuantityInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenQuantityInfo,"250");

ui_infoScreenQuantityLabel = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenQuantityLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenQuantityLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenQuantityLabel, lv_pct(25) );
lv_obj_set_y( ui_infoScreenQuantityLabel, lv_pct(0) );
lv_obj_set_align( ui_infoScreenQuantityLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenQuantityLabel,"gramos");

ui_infoScreenTimeLabel = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenTimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_infoScreenTimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_infoScreenTimeLabel, lv_pct(25) );
lv_obj_set_y( ui_infoScreenTimeLabel, lv_pct(15) );
lv_obj_set_align( ui_infoScreenTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenTimeLabel,"horas");

ui_infoScreenFuctionInfo = lv_label_create(ui_infoScreenTypeFood);
lv_obj_set_width( ui_infoScreenFuctionInfo, lv_pct(60));
lv_obj_set_height( ui_infoScreenFuctionInfo, lv_pct(8));
lv_obj_set_x( ui_infoScreenFuctionInfo, lv_pct(0) );
lv_obj_set_y( ui_infoScreenFuctionInfo, lv_pct(-35) );
lv_obj_set_align( ui_infoScreenFuctionInfo, LV_ALIGN_CENTER );
lv_label_set_text(ui_infoScreenFuctionInfo,"EN FUNCIONAMIENTO");
lv_obj_set_style_text_align(ui_infoScreenFuctionInfo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_infoScreenFuctionInfo, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_infoScreenFuctionInfo, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_infoScreenFuctionInfo, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_infoScreenFuctionInfo, lv_color_hex(0xD04C29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_infoScreenFuctionInfo, 157, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_infoScreenFuctionInfo, lv_color_hex(0x32B12E), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_infoScreenFuctionInfo, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_add_event_cb(ui_infoScreenInitButton, ui_event_infoScreenInitButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_infoScreenForceButton, ui_event_infoScreenForceButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_infoScreenConfiguratioButton, ui_event_infoScreenConfiguratioButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_infoScreenStopButton, ui_event_infoScreenStopButton, LV_EVENT_ALL, NULL);

}
