// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_initScreen_screen_init(void)
{
ui_initScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_initScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rightInitButton = lv_imgbtn_create(ui_initScreen);
lv_imgbtn_set_src(ui_rightInitButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowforward_png, NULL);
lv_imgbtn_set_src(ui_rightInitButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowforward_png, NULL);
lv_obj_set_width( ui_rightInitButton, lv_pct(10));
lv_obj_set_height( ui_rightInitButton, lv_pct(15));
lv_obj_set_x( ui_rightInitButton, lv_pct(40) );
lv_obj_set_y( ui_rightInitButton, lv_pct(0) );
lv_obj_set_align( ui_rightInitButton, LV_ALIGN_CENTER );

ui_leftInitButton = lv_imgbtn_create(ui_initScreen);
lv_imgbtn_set_src(ui_leftInitButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowback_png, NULL);
lv_imgbtn_set_src(ui_leftInitButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowback_png, NULL);
lv_obj_set_width( ui_leftInitButton, lv_pct(10));
lv_obj_set_height( ui_leftInitButton, lv_pct(15));
lv_obj_set_x( ui_leftInitButton, lv_pct(-40) );
lv_obj_set_y( ui_leftInitButton, lv_pct(0) );
lv_obj_set_align( ui_leftInitButton, LV_ALIGN_CENTER );

ui_initBodyText = lv_label_create(ui_initScreen);
lv_obj_set_width( ui_initBodyText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_initBodyText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_initBodyText, LV_ALIGN_CENTER );
lv_label_set_text(ui_initBodyText,"Este dispositivo fue disenado \npara cumplir los estandares\nde la alimentacion de los\nanimales en granjas \n\nDisenado por Taller Cartama\nMedellin, Colombia");
lv_obj_set_style_text_align(ui_initBodyText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_initBodyText, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_rightInitButton, ui_event_rightInitButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_leftInitButton, ui_event_leftInitButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_initScreen, ui_event_initScreen, LV_EVENT_ALL, NULL);

}
