// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_selectTimestampScreen_screen_init(void)
{
ui_selectTimestampScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_selectTimestampScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rightProcessButton = lv_imgbtn_create(ui_selectTimestampScreen);
lv_imgbtn_set_src(ui_rightProcessButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowforward_png, NULL);
lv_imgbtn_set_src(ui_rightProcessButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowforward_png, NULL);
lv_obj_set_width( ui_rightProcessButton, lv_pct(10));
lv_obj_set_height( ui_rightProcessButton, lv_pct(15));
lv_obj_set_x( ui_rightProcessButton, lv_pct(40) );
lv_obj_set_y( ui_rightProcessButton, lv_pct(0) );
lv_obj_set_align( ui_rightProcessButton, LV_ALIGN_CENTER );

ui_leftTimestampButton = lv_imgbtn_create(ui_selectTimestampScreen);
lv_imgbtn_set_src(ui_leftTimestampButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowback_png, NULL);
lv_imgbtn_set_src(ui_leftTimestampButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowback_png, NULL);
lv_obj_set_width( ui_leftTimestampButton, lv_pct(10));
lv_obj_set_height( ui_leftTimestampButton, lv_pct(15));
lv_obj_set_x( ui_leftTimestampButton, lv_pct(-40) );
lv_obj_set_y( ui_leftTimestampButton, lv_pct(0) );
lv_obj_set_align( ui_leftTimestampButton, LV_ALIGN_CENTER );

ui_selectTimestampHeaderText = lv_label_create(ui_selectTimestampScreen);
lv_obj_set_width( ui_selectTimestampHeaderText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectTimestampHeaderText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectTimestampHeaderText, lv_pct(0) );
lv_obj_set_y( ui_selectTimestampHeaderText, lv_pct(-25) );
lv_obj_set_align( ui_selectTimestampHeaderText, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectTimestampHeaderText,"Cada cuantas horas ? ");
lv_obj_set_style_text_align(ui_selectTimestampHeaderText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectTimestampHeaderText, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectTimestampBodyText = lv_label_create(ui_selectTimestampScreen);
lv_obj_set_width( ui_selectTimestampBodyText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectTimestampBodyText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selectTimestampBodyText, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectTimestampBodyText,"0");
lv_obj_set_style_text_font(ui_selectTimestampBodyText, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectTimestampBodyText2 = lv_label_create(ui_selectTimestampScreen);
lv_obj_set_width( ui_selectTimestampBodyText2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectTimestampBodyText2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectTimestampBodyText2, lv_pct(10) );
lv_obj_set_y( ui_selectTimestampBodyText2, lv_pct(0) );
lv_obj_set_align( ui_selectTimestampBodyText2, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectTimestampBodyText2,"h");
lv_obj_set_style_text_font(ui_selectTimestampBodyText2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectTimestampRemoveButton = lv_imgbtn_create(ui_selectTimestampScreen);
lv_imgbtn_set_src(ui_selectTimestampRemoveButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_remove_png, NULL);
lv_imgbtn_set_src(ui_selectTimestampRemoveButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_remove_png, NULL);
lv_obj_set_height( ui_selectTimestampRemoveButton, lv_pct(15));
lv_obj_set_width( ui_selectTimestampRemoveButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_selectTimestampRemoveButton, lv_pct(-15) );
lv_obj_set_y( ui_selectTimestampRemoveButton, lv_pct(25) );
lv_obj_set_align( ui_selectTimestampRemoveButton, LV_ALIGN_CENTER );

ui_selectTimestampAddButton = lv_imgbtn_create(ui_selectTimestampScreen);
lv_imgbtn_set_src(ui_selectTimestampAddButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_png, NULL);
lv_imgbtn_set_src(ui_selectTimestampAddButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_add_png, NULL);
lv_obj_set_height( ui_selectTimestampAddButton, lv_pct(15));
lv_obj_set_width( ui_selectTimestampAddButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_selectTimestampAddButton, lv_pct(15) );
lv_obj_set_y( ui_selectTimestampAddButton, lv_pct(25) );
lv_obj_set_align( ui_selectTimestampAddButton, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_rightProcessButton, ui_event_rightProcessButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_leftTimestampButton, ui_event_leftTimestampButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectTimestampRemoveButton, ui_event_selectTimestampRemoveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectTimestampAddButton, ui_event_selectTimestampAddButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectTimestampScreen, ui_event_selectTimestampScreen, LV_EVENT_ALL, NULL);

}
