// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_selectQuantityScreen_screen_init(void)
{
ui_selectQuantityScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_selectQuantityScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rightSelectQuantityButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_rightSelectQuantityButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowforward_png, NULL);
lv_imgbtn_set_src(ui_rightSelectQuantityButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowforward_png, NULL);
lv_obj_set_width( ui_rightSelectQuantityButton, lv_pct(10));
lv_obj_set_height( ui_rightSelectQuantityButton, lv_pct(15));
lv_obj_set_x( ui_rightSelectQuantityButton, lv_pct(40) );
lv_obj_set_y( ui_rightSelectQuantityButton, lv_pct(0) );
lv_obj_set_align( ui_rightSelectQuantityButton, LV_ALIGN_CENTER );

ui_leftSelectQuantityButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_leftSelectQuantityButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowback_png, NULL);
lv_imgbtn_set_src(ui_leftSelectQuantityButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowback_png, NULL);
lv_obj_set_width( ui_leftSelectQuantityButton, lv_pct(10));
lv_obj_set_height( ui_leftSelectQuantityButton, lv_pct(15));
lv_obj_set_x( ui_leftSelectQuantityButton, lv_pct(-40) );
lv_obj_set_y( ui_leftSelectQuantityButton, lv_pct(0) );
lv_obj_set_align( ui_leftSelectQuantityButton, LV_ALIGN_CENTER );

ui_selectQuantityHeaderText = lv_label_create(ui_selectQuantityScreen);
lv_obj_set_width( ui_selectQuantityHeaderText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectQuantityHeaderText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectQuantityHeaderText, lv_pct(0) );
lv_obj_set_y( ui_selectQuantityHeaderText, lv_pct(-25) );
lv_obj_set_align( ui_selectQuantityHeaderText, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectQuantityHeaderText,"Que cantidad deseas dar:");
lv_obj_set_style_text_align(ui_selectQuantityHeaderText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectQuantityHeaderText, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectQuantityBodyText = lv_label_create(ui_selectQuantityScreen);
lv_obj_set_width( ui_selectQuantityBodyText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectQuantityBodyText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selectQuantityBodyText, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectQuantityBodyText,"0");
lv_obj_set_style_text_font(ui_selectQuantityBodyText, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectQuantityBodyText2 = lv_label_create(ui_selectQuantityScreen);
lv_obj_set_width( ui_selectQuantityBodyText2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectQuantityBodyText2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectQuantityBodyText2, lv_pct(10) );
lv_obj_set_y( ui_selectQuantityBodyText2, lv_pct(0) );
lv_obj_set_align( ui_selectQuantityBodyText2, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectQuantityBodyText2,"gr");
lv_obj_set_style_text_font(ui_selectQuantityBodyText2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectQuantityRemoveButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_selectQuantityRemoveButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_remove_png, NULL);
lv_imgbtn_set_src(ui_selectQuantityRemoveButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_remove_png, NULL);
lv_obj_set_height( ui_selectQuantityRemoveButton, lv_pct(15));
lv_obj_set_width( ui_selectQuantityRemoveButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_selectQuantityRemoveButton, lv_pct(-15) );
lv_obj_set_y( ui_selectQuantityRemoveButton, lv_pct(25) );
lv_obj_set_align( ui_selectQuantityRemoveButton, LV_ALIGN_CENTER );

ui_selectQuantityAddButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_selectQuantityAddButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_add_png, NULL);
lv_imgbtn_set_src(ui_selectQuantityAddButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_add_png, NULL);
lv_obj_set_height( ui_selectQuantityAddButton, lv_pct(15));
lv_obj_set_width( ui_selectQuantityAddButton, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_selectQuantityAddButton, lv_pct(15) );
lv_obj_set_y( ui_selectQuantityAddButton, lv_pct(25) );
lv_obj_set_align( ui_selectQuantityAddButton, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_rightSelectQuantityButton, ui_event_rightSelectQuantityButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_leftSelectQuantityButton, ui_event_leftSelectQuantityButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectQuantityRemoveButton, ui_event_selectQuantityRemoveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectQuantityAddButton, ui_event_selectQuantityAddButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectQuantityScreen, ui_event_selectQuantityScreen, LV_EVENT_ALL, NULL);

}
