// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_selectFoodScreen_screen_init(void)
{
ui_selectFoodScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_selectFoodScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_selectFoodScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_selectFoodScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectFoodTypeButton1 = lv_btn_create(ui_selectFoodScreen);
lv_obj_set_width( ui_selectFoodTypeButton1, 140);
lv_obj_set_height( ui_selectFoodTypeButton1, 65);
lv_obj_set_x( ui_selectFoodTypeButton1, lv_pct(-19) );
lv_obj_set_y( ui_selectFoodTypeButton1, lv_pct(-15) );
lv_obj_set_align( ui_selectFoodTypeButton1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_selectFoodTypeButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_selectFoodTypeButton1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_selectFoodTypeButton1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_selectFoodTypeButton1, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_selectFoodTypeButton1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_selectFoodTypeButton1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_selectFoodTypeButton1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_selectFoodTypeButton1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton1, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeText1 = lv_label_create(ui_selectFoodTypeButton1);
lv_obj_set_width( ui_selectFoodTypeText1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectFoodTypeText1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selectFoodTypeText1, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectFoodTypeText1,"Peletizado");
lv_obj_set_style_text_color(ui_selectFoodTypeText1, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectFoodTypeText1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectFoodTypeText1, &ui_font_RegularFont, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_selectFoodTypeText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_selectFoodTypeText1, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_text_color(ui_selectFoodTypeText1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_selectFoodTypeText1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeButton2 = lv_btn_create(ui_selectFoodScreen);
lv_obj_set_width( ui_selectFoodTypeButton2, 140);
lv_obj_set_height( ui_selectFoodTypeButton2, 65);
lv_obj_set_x( ui_selectFoodTypeButton2, lv_pct(19) );
lv_obj_set_y( ui_selectFoodTypeButton2, lv_pct(-15) );
lv_obj_set_align( ui_selectFoodTypeButton2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_selectFoodTypeButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_selectFoodTypeButton2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_selectFoodTypeButton2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_selectFoodTypeButton2, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_selectFoodTypeButton2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_selectFoodTypeButton2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton2, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeText2 = lv_label_create(ui_selectFoodTypeButton2);
lv_obj_set_width( ui_selectFoodTypeText2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectFoodTypeText2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selectFoodTypeText2, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectFoodTypeText2,"Croquetas");
lv_obj_set_style_text_color(ui_selectFoodTypeText2, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectFoodTypeText2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectFoodTypeText2, &ui_font_RegularFont, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_selectFoodTypeText2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_selectFoodTypeText2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeButton3 = lv_btn_create(ui_selectFoodScreen);
lv_obj_set_width( ui_selectFoodTypeButton3, 140);
lv_obj_set_height( ui_selectFoodTypeButton3, 65);
lv_obj_set_x( ui_selectFoodTypeButton3, lv_pct(19) );
lv_obj_set_y( ui_selectFoodTypeButton3, lv_pct(14) );
lv_obj_set_align( ui_selectFoodTypeButton3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_selectFoodTypeButton3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_selectFoodTypeButton3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_selectFoodTypeButton3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_selectFoodTypeButton3, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_selectFoodTypeButton3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_selectFoodTypeButton3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton3, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeText3 = lv_label_create(ui_selectFoodTypeButton3);
lv_obj_set_width( ui_selectFoodTypeText3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectFoodTypeText3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selectFoodTypeText3, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectFoodTypeText3,"Cubos de\nHeno");
lv_obj_set_style_text_color(ui_selectFoodTypeText3, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectFoodTypeText3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_selectFoodTypeText3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectFoodTypeText3, &ui_font_RegularFont, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_selectFoodTypeText3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_selectFoodTypeText3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeButton4 = lv_btn_create(ui_selectFoodScreen);
lv_obj_set_width( ui_selectFoodTypeButton4, 140);
lv_obj_set_height( ui_selectFoodTypeButton4, 65);
lv_obj_set_x( ui_selectFoodTypeButton4, lv_pct(-19) );
lv_obj_set_y( ui_selectFoodTypeButton4, lv_pct(14) );
lv_obj_set_align( ui_selectFoodTypeButton4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_selectFoodTypeButton4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_selectFoodTypeButton4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_selectFoodTypeButton4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_selectFoodTypeButton4, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_selectFoodTypeButton4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_selectFoodTypeButton4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_selectFoodTypeButton4, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_selectFoodTypeButton4, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeText4 = lv_label_create(ui_selectFoodTypeButton4);
lv_obj_set_width( ui_selectFoodTypeText4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectFoodTypeText4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selectFoodTypeText4, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectFoodTypeText4,"Mixto");
lv_obj_set_style_text_color(ui_selectFoodTypeText4, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectFoodTypeText4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_selectFoodTypeText4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectFoodTypeText4, &ui_font_RegularFont, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_selectFoodTypeText4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_text_opa(ui_selectFoodTypeText4, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectFoodTypeHeaderText = lv_label_create(ui_selectFoodScreen);
lv_obj_set_width( ui_selectFoodTypeHeaderText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectFoodTypeHeaderText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectFoodTypeHeaderText, lv_pct(0) );
lv_obj_set_y( ui_selectFoodTypeHeaderText, lv_pct(-40) );
lv_obj_set_align( ui_selectFoodTypeHeaderText, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectFoodTypeHeaderText,"¿Qué tipo de alimento deseas dispensar?");
lv_obj_set_style_text_color(ui_selectFoodTypeHeaderText, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectFoodTypeHeaderText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_selectFoodTypeHeaderText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectFoodTypeHeaderText, &ui_font_BoldFont, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_blend_mode(ui_selectFoodTypeHeaderText, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectFoodFooter = lv_label_create(ui_selectFoodScreen);
lv_obj_set_width( ui_selectFoodFooter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectFoodFooter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectFoodFooter, lv_pct(0) );
lv_obj_set_y( ui_selectFoodFooter, lv_pct(44) );
lv_obj_set_align( ui_selectFoodFooter, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectFoodFooter,"Ferus Smart - Elección inteligente para una nutrición saludable");
lv_obj_set_style_text_color(ui_selectFoodFooter, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectFoodFooter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectFoodFooter, &ui_font_RegularSmallFont, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_selectFoodTypeButton1, ui_event_selectFoodTypeButton1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectFoodTypeButton2, ui_event_selectFoodTypeButton2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectFoodTypeButton3, ui_event_selectFoodTypeButton3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectFoodTypeButton4, ui_event_selectFoodTypeButton4, LV_EVENT_ALL, NULL);

}
