// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_TouchScreen_screen_init(void)
{
ui_TouchScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_TouchScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TouchScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TouchScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TouchScreenHeader = lv_label_create(ui_TouchScreen);
lv_obj_set_width( ui_TouchScreenHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TouchScreenHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TouchScreenHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_TouchScreenHeader,"Toca la pantalla para iniciar");
lv_obj_set_style_text_color(ui_TouchScreenHeader, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TouchScreenHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TouchScreenHeader, &ui_font_BoldMediumFont, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TouchScreen, ui_event_TouchScreen, LV_EVENT_ALL, NULL);

}
