// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_welcomeScreen_screen_init(void)
{
ui_welcomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_welcomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LogoWelcomeImage = lv_img_create(ui_welcomeScreen);
lv_img_set_src(ui_LogoWelcomeImage, &ui_img_horsesilhouette_png);
lv_obj_set_width( ui_LogoWelcomeImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LogoWelcomeImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LogoWelcomeImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LogoWelcomeImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LogoWelcomeImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_LogoWelcomeImage,70);

ui_headerWelcomeName = lv_label_create(ui_welcomeScreen);
lv_obj_set_width( ui_headerWelcomeName, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_headerWelcomeName, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_headerWelcomeName, lv_pct(0) );
lv_obj_set_y( ui_headerWelcomeName, lv_pct(-35) );
lv_obj_set_align( ui_headerWelcomeName, LV_ALIGN_CENTER );
lv_label_set_text(ui_headerWelcomeName,"BIENVENIDO");
lv_obj_set_style_text_font(ui_headerWelcomeName, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_footer_WelcomeText = lv_label_create(ui_welcomeScreen);
lv_obj_set_width( ui_footer_WelcomeText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_footer_WelcomeText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_footer_WelcomeText, lv_pct(0) );
lv_obj_set_y( ui_footer_WelcomeText, lv_pct(35) );
lv_obj_set_align( ui_footer_WelcomeText, LV_ALIGN_CENTER );
lv_label_set_text(ui_footer_WelcomeText,"Bienestar para tu caballo");

ui_rightWelcomeButton = lv_imgbtn_create(ui_welcomeScreen);
lv_imgbtn_set_src(ui_rightWelcomeButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrowforward_png, NULL);
lv_imgbtn_set_src(ui_rightWelcomeButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrowforward_png, NULL);
lv_obj_set_width( ui_rightWelcomeButton, lv_pct(10));
lv_obj_set_height( ui_rightWelcomeButton, lv_pct(15));
lv_obj_set_x( ui_rightWelcomeButton, lv_pct(40) );
lv_obj_set_y( ui_rightWelcomeButton, lv_pct(0) );
lv_obj_set_align( ui_rightWelcomeButton, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_LogoWelcomeImage, ui_event_LogoWelcomeImage, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_rightWelcomeButton, ui_event_rightWelcomeButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_welcomeScreen, ui_event_welcomeScreen, LV_EVENT_ALL, NULL);

}
