// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#ifndef _FERUS_PROJECT_UI_UI_H
#define _FERUS_PROJECT_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
void ui_event_welcomeScreen( lv_event_t * e);
extern lv_obj_t *ui_welcomeScreen;
extern lv_obj_t *ui_Logo;
// SCREEN: ui_helloScreen
void ui_helloScreen_screen_init(void);
void ui_event_helloScreen( lv_event_t * e);
extern lv_obj_t *ui_helloScreen;
void ui_event_rightHelloButton( lv_event_t * e);
extern lv_obj_t *ui_rightHelloButton;
extern lv_obj_t *ui_helloScreenHeader;
// SCREEN: ui_initScreen
void ui_initScreen_screen_init(void);
void ui_event_initScreen( lv_event_t * e);
extern lv_obj_t *ui_initScreen;
void ui_event_rightInitButton( lv_event_t * e);
extern lv_obj_t *ui_rightInitButton;
extern lv_obj_t *ui_initScreenMainText;
extern lv_obj_t *ui_initScreenBodyText;
void ui_event_leftInitButton( lv_event_t * e);
extern lv_obj_t *ui_leftInitButton;
// SCREEN: ui_TouchScreen
void ui_TouchScreen_screen_init(void);
void ui_event_TouchScreen( lv_event_t * e);
extern lv_obj_t *ui_TouchScreen;
extern lv_obj_t *ui_TouchScreenHeader;
// SCREEN: ui_selectFoodScreen
void ui_selectFoodScreen_screen_init(void);
extern lv_obj_t *ui_selectFoodScreen;
void ui_event_selectFoodTypeButton1( lv_event_t * e);
extern lv_obj_t *ui_selectFoodTypeButton1;
extern lv_obj_t *ui_selectFoodTypeText1;
void ui_event_selectFoodTypeButton2( lv_event_t * e);
extern lv_obj_t *ui_selectFoodTypeButton2;
extern lv_obj_t *ui_selectFoodTypeText2;
void ui_event_selectFoodTypeButton3( lv_event_t * e);
extern lv_obj_t *ui_selectFoodTypeButton3;
extern lv_obj_t *ui_selectFoodTypeText3;
void ui_event_selectFoodTypeButton4( lv_event_t * e);
extern lv_obj_t *ui_selectFoodTypeButton4;
extern lv_obj_t *ui_selectFoodTypeText4;
extern lv_obj_t *ui_selectFoodTypeHeaderText;
extern lv_obj_t *ui_selectFoodFooter;
// SCREEN: ui_selectQuantityScreen
void ui_selectQuantityScreen_screen_init(void);
void ui_event_selectQuantityScreen( lv_event_t * e);
extern lv_obj_t *ui_selectQuantityScreen;
void ui_event_rightSelectQuantityButton( lv_event_t * e);
extern lv_obj_t *ui_rightSelectQuantityButton;
void ui_event_leftSelectQuantityButton( lv_event_t * e);
extern lv_obj_t *ui_leftSelectQuantityButton;
extern lv_obj_t *ui_selectQuantityHeaderText;
extern lv_obj_t *ui_selectQuantityBodyText;
extern lv_obj_t *ui_selectQuantityBodyText2;
void ui_event_selectQuantityRemoveButton( lv_event_t * e);
extern lv_obj_t *ui_selectQuantityRemoveButton;
void ui_event_selectQuantityAddButton( lv_event_t * e);
extern lv_obj_t *ui_selectQuantityAddButton;
extern lv_obj_t *ui_selectQuantityFooter;
// SCREEN: ui_selectTimestampScreen
void ui_selectTimestampScreen_screen_init(void);
void ui_event_selectTimestampScreen( lv_event_t * e);
extern lv_obj_t *ui_selectTimestampScreen;
void ui_event_rightProcessButton( lv_event_t * e);
extern lv_obj_t *ui_rightProcessButton;
void ui_event_leftTimestampButton( lv_event_t * e);
extern lv_obj_t *ui_leftTimestampButton;
extern lv_obj_t *ui_selectTimestampHeaderText;
extern lv_obj_t *ui_selectTimestampBodyText;
void ui_event_selectTimestampRemoveButton( lv_event_t * e);
extern lv_obj_t *ui_selectTimestampRemoveButton;
extern lv_obj_t *ui_selectTimestampBodyText1;
extern lv_obj_t *ui_selectTimestampBodyText2;
void ui_event_selectTimestampAddButton( lv_event_t * e);
extern lv_obj_t *ui_selectTimestampAddButton;
extern lv_obj_t *ui_selectTimestampBodyText3;
extern lv_obj_t *ui_selectTimeFooter;
extern lv_obj_t *ui_selectTimestampFooter;
// SCREEN: ui_infoScreenTypeFood
void ui_infoScreenTypeFood_screen_init(void);
extern lv_obj_t *ui_infoScreenTypeFood;
extern lv_obj_t *ui_tableView;
extern lv_obj_t *ui_infoScreenFuctionInfo;
void ui_event_infoScreenInitButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenInitButton;
extern lv_obj_t *ui_Label11;
void ui_event_infoScreenDispenseButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenDispenseButton;
extern lv_obj_t *ui_Label12;
void ui_event_infoScreenConfiguratioButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenConfiguratioButton;
extern lv_obj_t *ui_Label13;
void ui_event_infoScreenStopButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenStopButton;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_infoScreenSummaryInfo;
extern lv_obj_t *ui_infoScreenTypeFoodHeader;
extern lv_obj_t *ui_infoScreenTypeFoodInfo;
extern lv_obj_t *ui_infoScreenQuantityHeader;
extern lv_obj_t *ui_infoScreenQuantityInfo;
extern lv_obj_t *ui_infoScreenQuantityTag;
extern lv_obj_t *ui_infoScreenFrecuencyHeader;
extern lv_obj_t *ui_infoScreenFrecuencyInfo;
extern lv_obj_t *ui_infoScreenFrecuencyHoursTag;
extern lv_obj_t *ui_infoScreenFrecuencyMinutesInfo;
extern lv_obj_t *ui_infoScreenFrecuencyMinutesTag;
extern lv_obj_t *ui_infoScreenFooter;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ferus_smart_logo_png);   // assets/ferus_smart_logo.png
LV_IMG_DECLARE( ui_img_arrow_forward_png);   // assets/arrow_forward.png
LV_IMG_DECLARE( ui_img_arrow_back_png);   // assets/arrow_back.png
LV_IMG_DECLARE( ui_img_difference_white_png);   // assets/difference_white.png
LV_IMG_DECLARE( ui_img_plus_white_png);   // assets/plus_white.png
LV_IMG_DECLARE( ui_img_table_png);   // assets/table.png

LV_FONT_DECLARE( ui_font_BoldBigFont);
LV_FONT_DECLARE( ui_font_BoldFont);
LV_FONT_DECLARE( ui_font_BoldMediumFont);
LV_FONT_DECLARE( ui_font_RegularFont);
LV_FONT_DECLARE( ui_font_RegularSmallFont);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
