// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_initScreen_screen_init(void)
{
ui_initScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_initScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_initScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_initScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rightInitButton = lv_imgbtn_create(ui_initScreen);
lv_imgbtn_set_src(ui_rightInitButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrow_forward_png, NULL);
lv_imgbtn_set_src(ui_rightInitButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrow_forward_png, NULL);
lv_obj_set_width( ui_rightInitButton, 65);
lv_obj_set_height( ui_rightInitButton, 65);
lv_obj_set_x( ui_rightInitButton, lv_pct(42) );
lv_obj_set_y( ui_rightInitButton, lv_pct(0) );
lv_obj_set_align( ui_rightInitButton, LV_ALIGN_CENTER );

ui_initScreenMainText = lv_label_create(ui_initScreen);
lv_obj_set_width( ui_initScreenMainText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_initScreenMainText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_initScreenMainText, -87 );
lv_obj_set_y( ui_initScreenMainText, -110 );
lv_obj_set_align( ui_initScreenMainText, LV_ALIGN_CENTER );
lv_label_set_text(ui_initScreenMainText,"Ferus Smart");
lv_obj_set_style_text_color(ui_initScreenMainText, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_initScreenMainText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_initScreenMainText, &ui_font_BoldFont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_initScreenBodyText = lv_label_create(ui_initScreen);
lv_obj_set_width( ui_initScreenBodyText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_initScreenBodyText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_initScreenBodyText, LV_ALIGN_CENTER );
lv_label_set_text(ui_initScreenBodyText,"	       		    				    es un alimentador\nautomático que permite \nescoger la cantidad y tiempo\nde alimentación según la\nnecesidad del animal, \nayudando a mejorar su salud\ntanto física como mental.\n\n\nDiseñado por Taller Cartama\nMedellin, Colombia.");
lv_obj_set_style_text_color(ui_initScreenBodyText, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_initScreenBodyText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_initScreenBodyText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_initScreenBodyText, &ui_font_RegularFont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_leftInitButton = lv_imgbtn_create(ui_initScreen);
lv_imgbtn_set_src(ui_leftInitButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrow_back_png, NULL);
lv_imgbtn_set_src(ui_leftInitButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrow_back_png, NULL);
lv_obj_set_width( ui_leftInitButton, 65);
lv_obj_set_height( ui_leftInitButton, 65);
lv_obj_set_x( ui_leftInitButton, lv_pct(-42) );
lv_obj_set_y( ui_leftInitButton, lv_pct(0) );
lv_obj_set_align( ui_leftInitButton, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_rightInitButton, ui_event_rightInitButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_leftInitButton, ui_event_leftInitButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_initScreen, ui_event_initScreen, LV_EVENT_ALL, NULL);

}
