// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "../ui.h"

void ui_selectQuantityScreen_screen_init(void)
{
ui_selectQuantityScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_selectQuantityScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_selectQuantityScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_selectQuantityScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_rightSelectQuantityButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_rightSelectQuantityButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrow_forward_png, NULL);
lv_imgbtn_set_src(ui_rightSelectQuantityButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrow_forward_png, NULL);
lv_obj_set_width( ui_rightSelectQuantityButton, 65);
lv_obj_set_height( ui_rightSelectQuantityButton, 65);
lv_obj_set_x( ui_rightSelectQuantityButton, lv_pct(42) );
lv_obj_set_y( ui_rightSelectQuantityButton, lv_pct(0) );
lv_obj_set_align( ui_rightSelectQuantityButton, LV_ALIGN_CENTER );

ui_leftSelectQuantityButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_leftSelectQuantityButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_arrow_back_png, NULL);
lv_imgbtn_set_src(ui_leftSelectQuantityButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_arrow_back_png, NULL);
lv_obj_set_width( ui_leftSelectQuantityButton, 65);
lv_obj_set_height( ui_leftSelectQuantityButton, 65);
lv_obj_set_x( ui_leftSelectQuantityButton, lv_pct(-42) );
lv_obj_set_y( ui_leftSelectQuantityButton, lv_pct(0) );
lv_obj_set_align( ui_leftSelectQuantityButton, LV_ALIGN_CENTER );

ui_selectQuantityHeaderText = lv_label_create(ui_selectQuantityScreen);
lv_obj_set_width( ui_selectQuantityHeaderText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectQuantityHeaderText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectQuantityHeaderText, lv_pct(0) );
lv_obj_set_y( ui_selectQuantityHeaderText, lv_pct(-40) );
lv_obj_set_align( ui_selectQuantityHeaderText, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectQuantityHeaderText,"¿Qué cantidad deseas dispensar?");
lv_obj_set_style_text_color(ui_selectQuantityHeaderText, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectQuantityHeaderText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_selectQuantityHeaderText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectQuantityHeaderText, &ui_font_BoldFont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectQuantityBodyText = lv_label_create(ui_selectQuantityScreen);
lv_obj_set_width( ui_selectQuantityBodyText, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectQuantityBodyText, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectQuantityBodyText, lv_pct(-12) );
lv_obj_set_y( ui_selectQuantityBodyText, lv_pct(-13) );
lv_obj_set_align( ui_selectQuantityBodyText, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectQuantityBodyText,"000");
lv_obj_set_style_text_color(ui_selectQuantityBodyText, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectQuantityBodyText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectQuantityBodyText, &lv_font_montserrat_44, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectQuantityBodyText2 = lv_label_create(ui_selectQuantityScreen);
lv_obj_set_width( ui_selectQuantityBodyText2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectQuantityBodyText2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectQuantityBodyText2, lv_pct(11) );
lv_obj_set_y( ui_selectQuantityBodyText2, lv_pct(-11) );
lv_obj_set_align( ui_selectQuantityBodyText2, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectQuantityBodyText2,"Gramos");
lv_obj_set_style_text_color(ui_selectQuantityBodyText2, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectQuantityBodyText2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectQuantityBodyText2, &ui_font_RegularFont, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selectQuantityRemoveButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_selectQuantityRemoveButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_difference_white_png, NULL);
lv_imgbtn_set_src(ui_selectQuantityRemoveButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_difference_white_png, NULL);
lv_obj_set_width( ui_selectQuantityRemoveButton, 65);
lv_obj_set_height( ui_selectQuantityRemoveButton, 65);
lv_obj_set_x( ui_selectQuantityRemoveButton, lv_pct(-11) );
lv_obj_set_y( ui_selectQuantityRemoveButton, lv_pct(14) );
lv_obj_set_align( ui_selectQuantityRemoveButton, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_selectQuantityRemoveButton, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_selectQuantityRemoveButton, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_selectQuantityRemoveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_selectQuantityRemoveButton, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_selectQuantityRemoveButton, lv_color_hex(0x514949), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_selectQuantityRemoveButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_selectQuantityRemoveButton, 3, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_selectQuantityRemoveButton, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_selectQuantityRemoveButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_selectQuantityRemoveButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_selectQuantityRemoveButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectQuantityAddButton = lv_imgbtn_create(ui_selectQuantityScreen);
lv_imgbtn_set_src(ui_selectQuantityAddButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_plus_white_png, NULL);
lv_imgbtn_set_src(ui_selectQuantityAddButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_plus_white_png, NULL);
lv_obj_set_width( ui_selectQuantityAddButton, 65);
lv_obj_set_height( ui_selectQuantityAddButton, 65);
lv_obj_set_x( ui_selectQuantityAddButton, lv_pct(11) );
lv_obj_set_y( ui_selectQuantityAddButton, lv_pct(14) );
lv_obj_set_align( ui_selectQuantityAddButton, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_selectQuantityAddButton, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_selectQuantityAddButton, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_selectQuantityAddButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_selectQuantityAddButton, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor(ui_selectQuantityAddButton, lv_color_hex(0x514949), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_selectQuantityAddButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_selectQuantityAddButton, 5, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_bg_color(ui_selectQuantityAddButton, lv_color_hex(0x808122), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_selectQuantityAddButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor(ui_selectQuantityAddButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_selectQuantityAddButton, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_selectQuantityFooter = lv_label_create(ui_selectQuantityScreen);
lv_obj_set_width( ui_selectQuantityFooter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selectQuantityFooter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_selectQuantityFooter, lv_pct(0) );
lv_obj_set_y( ui_selectQuantityFooter, lv_pct(44) );
lv_obj_set_align( ui_selectQuantityFooter, LV_ALIGN_CENTER );
lv_label_set_text(ui_selectQuantityFooter,"FerusSmart - Elección inteligente para una nutrición saludable");
lv_obj_set_style_text_color(ui_selectQuantityFooter, lv_color_hex(0x514949), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_selectQuantityFooter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selectQuantityFooter, &ui_font_RegularSmallFont, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_rightSelectQuantityButton, ui_event_rightSelectQuantityButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_leftSelectQuantityButton, ui_event_leftSelectQuantityButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectQuantityRemoveButton, ui_event_selectQuantityRemoveButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectQuantityAddButton, ui_event_selectQuantityAddButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_selectQuantityScreen, ui_event_selectQuantityScreen, LV_EVENT_ALL, NULL);

}
