// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
void ui_event_welcomeScreen( lv_event_t * e);
lv_obj_t *ui_welcomeScreen;
void ui_event_LogoWelcomeImage( lv_event_t * e);
lv_obj_t *ui_LogoWelcomeImage;
lv_obj_t *ui_headerWelcomeName;
lv_obj_t *ui_footer_WelcomeText;
void ui_event_rightWelcomeButton( lv_event_t * e);
lv_obj_t *ui_rightWelcomeButton;

// SCREEN: ui_helloScreen
void ui_helloScreen_screen_init(void);
void ui_event_helloScreen( lv_event_t * e);
lv_obj_t *ui_helloScreen;
lv_obj_t *ui_headerHelloText;
void ui_event_rightHelloButton( lv_event_t * e);
lv_obj_t *ui_rightHelloButton;
void ui_event_leftHelloButton( lv_event_t * e);
lv_obj_t *ui_leftHelloButton;

// SCREEN: ui_initScreen
void ui_initScreen_screen_init(void);
void ui_event_initScreen( lv_event_t * e);
lv_obj_t *ui_initScreen;
void ui_event_rightInitButton( lv_event_t * e);
lv_obj_t *ui_rightInitButton;
void ui_event_leftInitButton( lv_event_t * e);
lv_obj_t *ui_leftInitButton;
lv_obj_t *ui_initBodyText;

// SCREEN: ui_selectFoodScreen
void ui_selectFoodScreen_screen_init(void);
lv_obj_t *ui_selectFoodScreen;
void ui_event_selectFoodTypeButton2( lv_event_t * e);
lv_obj_t *ui_selectFoodTypeButton2;
lv_obj_t *ui_initFooterButtonText1;
lv_obj_t *ui_selectFoodTypeHeaderText;
void ui_event_selectFoodTypeButton1( lv_event_t * e);
lv_obj_t *ui_selectFoodTypeButton1;
lv_obj_t *ui_Label1;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_selectFoodTypeButton3;

// SCREEN: ui_selectQuantityScreen
void ui_selectQuantityScreen_screen_init(void);
void ui_event_selectQuantityScreen( lv_event_t * e);
lv_obj_t *ui_selectQuantityScreen;
void ui_event_rightSelectQuantityButton( lv_event_t * e);
lv_obj_t *ui_rightSelectQuantityButton;
void ui_event_leftSelectQuantityButton( lv_event_t * e);
lv_obj_t *ui_leftSelectQuantityButton;
lv_obj_t *ui_selectQuantityHeaderText;
lv_obj_t *ui_selectQuantityBodyText;
lv_obj_t *ui_selectQuantityBodyText2;
void ui_event_selectQuantityRemoveButton( lv_event_t * e);
lv_obj_t *ui_selectQuantityRemoveButton;
void ui_event_selectQuantityAddButton( lv_event_t * e);
lv_obj_t *ui_selectQuantityAddButton;

// SCREEN: ui_selectTimestampScreen
void ui_selectTimestampScreen_screen_init(void);
void ui_event_selectTimestampScreen( lv_event_t * e);
lv_obj_t *ui_selectTimestampScreen;
void ui_event_rightProcessButton( lv_event_t * e);
lv_obj_t *ui_rightProcessButton;
void ui_event_leftTimestampButton( lv_event_t * e);
lv_obj_t *ui_leftTimestampButton;
lv_obj_t *ui_selectTimestampHeaderText;
lv_obj_t *ui_selectTimestampBodyText;
lv_obj_t *ui_selectTimestampBodyText2;
void ui_event_selectTimestampRemoveButton( lv_event_t * e);
lv_obj_t *ui_selectTimestampRemoveButton;
void ui_event_selectTimestampAddButton( lv_event_t * e);
lv_obj_t *ui_selectTimestampAddButton;

// SCREEN: ui_infoScreenTypeFood
void ui_infoScreenTypeFood_screen_init(void);
lv_obj_t *ui_infoScreenTypeFood;
lv_obj_t *ui_infoScreenTypeFoodHeader;
lv_obj_t *ui_infoScreenQuantityHeader;
lv_obj_t *ui_infoScreenTimeHeader;
void ui_event_infoScreenInitButton( lv_event_t * e);
lv_obj_t *ui_infoScreenInitButton;
lv_obj_t *ui_Label11;
lv_obj_t *ui_Button3;
void ui_event_infoScreenForceButton( lv_event_t * e);
lv_obj_t *ui_infoScreenForceButton;
void ui_event_infoScreenConfiguratioButton( lv_event_t * e);
lv_obj_t *ui_infoScreenConfiguratioButton;
lv_obj_t *ui_Label13;
void ui_event_infoScreenStopButton( lv_event_t * e);
lv_obj_t *ui_infoScreenStopButton;
lv_obj_t *ui_Label14;
lv_obj_t *ui_infoScreenTypeFoodInfo;
lv_obj_t *ui_infoScreenTimeInfo;
lv_obj_t *ui_infoScreenQuantityInfo;
lv_obj_t *ui_infoScreenQuantityLabel;
lv_obj_t *ui_infoScreenTimeLabel;
lv_obj_t *ui_infoScreenFuctionInfo;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_welcomeScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_helloScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_LogoWelcomeImage( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_helloScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_rightWelcomeButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_helloScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_helloScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_initScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_welcomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_rightHelloButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_initScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_leftHelloButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_welcomeScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_initScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_selectFoodScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_helloScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_rightInitButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectFoodScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_leftInitButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_helloScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_selectFoodTypeButton2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectQuantityScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_CLICKED) {
      foodType2( e );
}
}
void ui_event_selectFoodTypeButton1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectQuantityScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_CLICKED) {
      foodType1( e );
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectQuantityScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_CLICKED) {
      foodType3( e );
}
}
void ui_event_selectQuantityScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_selectTimestampScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_selectFoodScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_rightSelectQuantityButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectTimestampScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_leftSelectQuantityButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectFoodScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_selectQuantityRemoveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      removeSelectQuantityLongPressed( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      removeSelectQuantityClicked( e );
}
}
void ui_event_selectQuantityAddButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      addSelectQuantityClicked( e );
}
if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      addSelectQuantityLongPressed( e );
}
}
void ui_event_selectTimestampScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_infoScreenTypeFood, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_selectQuantityScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_rightProcessButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_infoScreenTypeFood, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0);
}
}
void ui_event_leftTimestampButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectQuantityScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
}
}
void ui_event_selectTimestampRemoveButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      removeSelectTimestampClicked( e );
}
if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      removeSelectTimestampLongPressed( e );
}
}
void ui_event_selectTimestampAddButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      addSelectTimestampClicked( e );
}
if ( event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
      addSelectTimestampLongPressed( e );
}
}
void ui_event_infoScreenInitButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      initFunction( e );
      _ui_state_modify( ui_infoScreenFuctionInfo, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
}
}
void ui_event_infoScreenForceButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      forceDistributionFunction( e );
}
}
void ui_event_infoScreenConfiguratioButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( ui_selectFoodScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
}
void ui_event_infoScreenStopButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      stopFunction( e );
      _ui_state_modify( ui_infoScreenFuctionInfo, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_welcomeScreen_screen_init();
ui_helloScreen_screen_init();
ui_initScreen_screen_init();
ui_selectFoodScreen_screen_init();
ui_selectQuantityScreen_screen_init();
ui_selectTimestampScreen_screen_init();
ui_infoScreenTypeFood_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_welcomeScreen);
}
