// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#ifndef _FERUS_PROJECT_UI_UI_H
#define _FERUS_PROJECT_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_welcomeScreen
void ui_welcomeScreen_screen_init(void);
void ui_event_welcomeScreen( lv_event_t * e);
extern lv_obj_t *ui_welcomeScreen;
void ui_event_LogoWelcomeImage( lv_event_t * e);
extern lv_obj_t *ui_LogoWelcomeImage;
extern lv_obj_t *ui_headerWelcomeName;
extern lv_obj_t *ui_footer_WelcomeText;
void ui_event_rightWelcomeButton( lv_event_t * e);
extern lv_obj_t *ui_rightWelcomeButton;
// SCREEN: ui_helloScreen
void ui_helloScreen_screen_init(void);
void ui_event_helloScreen( lv_event_t * e);
extern lv_obj_t *ui_helloScreen;
extern lv_obj_t *ui_headerHelloText;
void ui_event_rightHelloButton( lv_event_t * e);
extern lv_obj_t *ui_rightHelloButton;
void ui_event_leftHelloButton( lv_event_t * e);
extern lv_obj_t *ui_leftHelloButton;
// SCREEN: ui_initScreen
void ui_initScreen_screen_init(void);
void ui_event_initScreen( lv_event_t * e);
extern lv_obj_t *ui_initScreen;
void ui_event_rightInitButton( lv_event_t * e);
extern lv_obj_t *ui_rightInitButton;
void ui_event_leftInitButton( lv_event_t * e);
extern lv_obj_t *ui_leftInitButton;
extern lv_obj_t *ui_initBodyText;
// SCREEN: ui_selectFoodScreen
void ui_selectFoodScreen_screen_init(void);
extern lv_obj_t *ui_selectFoodScreen;
void ui_event_selectFoodTypeButton2( lv_event_t * e);
extern lv_obj_t *ui_selectFoodTypeButton2;
extern lv_obj_t *ui_initFooterButtonText1;
extern lv_obj_t *ui_selectFoodTypeHeaderText;
void ui_event_selectFoodTypeButton1( lv_event_t * e);
extern lv_obj_t *ui_selectFoodTypeButton1;
extern lv_obj_t *ui_Label1;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_selectFoodTypeButton3;
// SCREEN: ui_selectQuantityScreen
void ui_selectQuantityScreen_screen_init(void);
void ui_event_selectQuantityScreen( lv_event_t * e);
extern lv_obj_t *ui_selectQuantityScreen;
void ui_event_rightSelectQuantityButton( lv_event_t * e);
extern lv_obj_t *ui_rightSelectQuantityButton;
void ui_event_leftSelectQuantityButton( lv_event_t * e);
extern lv_obj_t *ui_leftSelectQuantityButton;
extern lv_obj_t *ui_selectQuantityHeaderText;
extern lv_obj_t *ui_selectQuantityBodyText;
extern lv_obj_t *ui_selectQuantityBodyText2;
void ui_event_selectQuantityRemoveButton( lv_event_t * e);
extern lv_obj_t *ui_selectQuantityRemoveButton;
void ui_event_selectQuantityAddButton( lv_event_t * e);
extern lv_obj_t *ui_selectQuantityAddButton;
// SCREEN: ui_selectTimestampScreen
void ui_selectTimestampScreen_screen_init(void);
void ui_event_selectTimestampScreen( lv_event_t * e);
extern lv_obj_t *ui_selectTimestampScreen;
void ui_event_rightProcessButton( lv_event_t * e);
extern lv_obj_t *ui_rightProcessButton;
void ui_event_leftTimestampButton( lv_event_t * e);
extern lv_obj_t *ui_leftTimestampButton;
extern lv_obj_t *ui_selectTimestampHeaderText;
extern lv_obj_t *ui_selectTimestampBodyText;
extern lv_obj_t *ui_selectTimestampBodyText2;
void ui_event_selectTimestampRemoveButton( lv_event_t * e);
extern lv_obj_t *ui_selectTimestampRemoveButton;
void ui_event_selectTimestampAddButton( lv_event_t * e);
extern lv_obj_t *ui_selectTimestampAddButton;
// SCREEN: ui_infoScreenTypeFood
void ui_infoScreenTypeFood_screen_init(void);
extern lv_obj_t *ui_infoScreenTypeFood;
extern lv_obj_t *ui_infoScreenTypeFoodHeader;
extern lv_obj_t *ui_infoScreenQuantityHeader;
extern lv_obj_t *ui_infoScreenTimeHeader;
void ui_event_infoScreenInitButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenInitButton;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Button3;
void ui_event_infoScreenForceButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenForceButton;
void ui_event_infoScreenConfiguratioButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenConfiguratioButton;
extern lv_obj_t *ui_Label13;
void ui_event_infoScreenStopButton( lv_event_t * e);
extern lv_obj_t *ui_infoScreenStopButton;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_infoScreenTypeFoodInfo;
extern lv_obj_t *ui_infoScreenTimeInfo;
extern lv_obj_t *ui_infoScreenQuantityInfo;
extern lv_obj_t *ui_infoScreenQuantityLabel;
extern lv_obj_t *ui_infoScreenTimeLabel;
extern lv_obj_t *ui_infoScreenFuctionInfo;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_horsesilhouette_png);   // assets/horseSilhouette.png
LV_IMG_DECLARE( ui_img_arrowforward_png);   // assets/arrowForward.png
LV_IMG_DECLARE( ui_img_arrowback_png);   // assets/arrowBack.png
LV_IMG_DECLARE( ui_img_remove_png);   // assets/remove.png
LV_IMG_DECLARE( ui_img_add_png);   // assets/add.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
