// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Ferus_Project_UI

#include "ui.h"

void foodType2(lv_event_t * e)
{
	// Your code here
}

void foodType1(lv_event_t * e)
{
	// Your code here
}

void foodType3(lv_event_t * e)
{
	// Your code here
}

void removeSelectQuantityLongPressed(lv_event_t * e)
{
	// Your code here
}

void removeSelectQuantityClicked(lv_event_t * e)
{
	// Your code here
}

void addSelectQuantityClicked(lv_event_t * e)
{
	// Your code here
}

void addSelectQuantityLongPressed(lv_event_t * e)
{
	// Your code here
}

void removeSelectTimestampClicked(lv_event_t * e)
{
	// Your code here
}

void removeSelectTimestampLongPressed(lv_event_t * e)
{
	// Your code here
}

void addSelectTimestampClicked(lv_event_t * e)
{
	// Your code here
}

void addSelectTimestampLongPressed(lv_event_t * e)
{
	// Your code here
}

void initFunction(lv_event_t * e)
{
	// Your code here
}

void forceDistributionFunction(lv_event_t * e)
{
	// Your code here
}

void stopFunction(lv_event_t * e)
{
	// Your code here
}
